[project]
name = 'Consciousness-Expansion-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consciousness-expansion-techniques]
path = 'contracts/consciousness-expansion-techniques.clar'
clarity_version = 2
epoch = 2.5

[contracts.expanded-consciousness-nft]
path = 'contracts/expanded-consciousness-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.safety-protocols]
path = 'contracts/safety-protocols.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
